// SEARCH
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';

// USER PROFILE
export const SET_SELECTED_USER = 'SET_SELECTED_USER';
export const SET_FILTERED_USERS = 'SET_FILTERED_USERS';

// GLOBAL
export const SET_MESSAGE = 'SET_MESSAGE';
export const RESET_MESSAGE = 'RESET_MESSAGE';
